---
title: "practice"
author: "Grace Kim"
date: "11/28/2019"
output: html_document
---

This R markdown was used to practice the various ggplot mappings of the South Korean peninsula, and create the base images needed for the shiny app that moved through the various density maps of the different religous populations in Korea. 

```{r setup, include=FALSE}

# need all of our libraries!

knitr::opts_chunk$set(echo = TRUE)
require(rgdal)
library(ggplot2)
library(dplyr)
library(broom)
library(readxl)
library(janitor)
library(cartogram)
library(scales)
```


```{r Data cleaning}
# read in the korea religions dataset :D
x <- read_xlsx("Korea/raw-data/2015_Religions_Korea.xlsx") %>% 
  clean_names()

# need to clean the data for only the numbers in each religous group

clean <- x %>% 
  filter(gender == "Total") %>% 
  tail(17) %>% 
  select(-matches("age")) %>% 
  select(-matches("gender"))

# change column name of region names to id for joining the various datasets later

colnames(clean)[1]<-"id"

############################################################# 
############### START OF SHAPEFILE STUFF ####################
#############################################################


# Read in Shape files of the korean administrative area boundaries
shp <- readOGR("Korea/raw-data/KOR_adm/KOR_adm1.shp", stringsAsFactors = F)

# tidyed the data for the region :D, need the region name so that the longitude data points match up the various busan seoul other area names 
shp_df<- tidy(shp, region = "NAME_1")
head(shp_df)

joined <- inner_join(shp_df,clean, by = "id")
joined
#shp@data <- inner_join(shp@data,clean, by = "NAME_1")
#shp@data
```



```{r Mapping}
# create all the various images for the shiny app

png("Korea/graphics/populationKorea.png")
png("Korea/graphics/allReligionsKorea.png")
png("Korea/graphics/buddhismKorea.png")
png("Korea/graphics/christProtesKorea.png")
png("Korea/graphics/christCathKorea.png")
png("Korea/graphics/wonBuddhismKorea.png")
png("Korea/graphics/confucianismKorea.png")
png("Korea/graphics/cheondoismKorea.png")
png("Korea/graphics/noReligionKorea.png")

# need a dataframe that has only the names of the various south korea administrative 
# regions

cnames <- aggregate(cbind(long, lat) ~ id, data=joined, 
                    FUN=function(x)mean((x)))

# geom polygon to plot the map in ggplot :D
# needed to group each administrative regions by group
# just made completely separate maps for every image

ggplot() + 
  geom_polygon(data = joined, 
               aes(x = long, 
                  y = lat, 
                  group = group, 
                  fill = as.numeric(total)), 
               colour = "white",
               size=0, 
               alpha=0.9) + 
  scale_fill_gradient2(low = "white",
                       mid = scales::muted("light blue"),
                       high = "purple",
                       labels = comma) +
  theme_void() +
  labs(title = "South Korea population density based on geographic region",
       fill = "Population")+
  geom_label(data = cnames, aes(x=long, y=lat, label=id),size = 1.5) 
#  geom_text(data = cnames,aes(long, lat, label = id), size=2)

ggsave("Korea/graphics/populationKorea.png")

# Religious Total
ggplot() + 
  geom_polygon(data = joined, 
               aes(x = long, 
                  y = lat, 
                  group = group, 
                  fill = as.numeric(religious_total)), 
               colour = "white",
               size=0, 
               alpha=0.9) + 
  scale_fill_gradient2(low = "white",
                       mid = scales::muted("light blue"),
                       high = "purple",
                       labels = comma) +
  theme_void() +
  labs(title = "Population of religious individuals based on geographic region",
       fill = "Population")
ggsave("Korea/graphics/allReligionsKorea.png")

# Buddhism map
ggplot() + 
  geom_polygon(data = joined, 
               aes(x = long, 
                  y = lat, 
                  group = group, 
                  fill = as.numeric(buddhism)), 
               colour = "white",
               size=0, 
               alpha=0.9) + 
  scale_fill_gradient2(low = "white",
                       mid = scales::muted("light blue"),
                       high = "purple",
                       labels = comma) +
  theme_void() +
  labs(title = "Population of Buddhists based on geographic region",
       fill = "Population")
ggsave("Korea/graphics/buddhismKorea.png")

# Christian Protestant map
ggplot() + 
  geom_polygon(data = joined, 
               aes(x = long, 
                  y = lat, 
                  group = group, 
                  fill = as.numeric(christianity_protestant)), 
               colour = "white",
               size=0, 
               alpha=0.9) + 
  scale_fill_gradient2(low = "white",
                       mid = scales::muted("light blue"),
                       high = "purple",
                       labels = comma) +
  theme_void() +
  labs(title = "Population of Protestant Christians based on geographic region",
       fill = "Population")
ggsave("Korea/graphics/christProtesKorea.png")

# Christian Catholic map
ggplot() + 
  geom_polygon(data = joined, 
               aes(x = long, 
                  y = lat, 
                  group = group, 
                  fill = as.numeric(christianity_catholic)), 
               colour = "white",
               size=0, 
               alpha=0.9) + 
  scale_fill_gradient2(low = "white",
                       mid = scales::muted("light blue"),
                       high = "purple",
                       labels = comma) +
  theme_void() +
  labs(title = "Population of Catholic Christians based on geographic region",
       fill = "Population")
ggsave("Korea/graphics/christCathKorea.png")

# Won Buddhism map
ggplot() + 
  geom_polygon(data = joined, 
               aes(x = long, 
                  y = lat, 
                  group = group, 
                  fill = as.numeric(won_buddhism)), 
               colour = "white",
               size=0, 
               alpha=0.9) + 
  scale_fill_gradient2(low = "white",
                       mid = scales::muted("light blue"),
                       high = "purple",
                       labels = comma) +
  theme_void() +
  labs(title = "Population of Won Buddhists based on geographic region",
       fill = "Population")
ggsave("Korea/graphics/wonBuddhismKorea.png")

# Confucianism map
ggplot() + 
  geom_polygon(data = joined, 
               aes(x = long, 
                  y = lat, 
                  group = group, 
                  fill = as.numeric(confucianism)), 
               colour = "white",
               size=0, 
               alpha=0.9) + 
  scale_fill_gradient2(low = "white",
                       mid = scales::muted("light blue"),
                       high = "purple",
                       labels = comma) +
  theme_void() +
  labs(title = "Population of Confucianists based on geographic region",
       fill = "Population")
ggsave("Korea/graphics/confucianismKorea.png")


# Confucianism map
ggplot() + 
  geom_polygon(data = joined, 
               aes(x = long, 
                  y = lat, 
                  group = group, 
                  fill = as.numeric(cheondoism)), 
               colour = "white",
               size=0, 
               alpha=0.9) + 
  scale_fill_gradient2(low = "white",
                       mid = scales::muted("light blue"),
                       high = "purple",
                       labels = comma) +
  theme_void() +
  labs(title = "Population of Cheondoists based on geographic region",
       fill = "Population")
ggsave("Korea/graphics/cheondoismKorea.png")


# no religion map
ggplot() + 
  geom_polygon(data = joined, 
               aes(x = long, 
                  y = lat, 
                  group = group, 
                  fill = as.numeric(no_religion)), 
               colour = "white",
               size=0, 
               alpha=0.9) + 
  scale_fill_gradient2(low = "white",
                       mid = scales::muted("light blue"),
                       high = "purple",
                       labels = comma) +
  theme_void() +
  labs(title = "Population of non-religious individuals based on geographic region",
       fill = "Population")
ggsave("Korea/graphics/noReligionKorea.png")

```

